discovery:
  exclusions:
  - ignored_folder/
  - test_ignored.py
engine:
  runtime: pytest
pinned-tests:
- test.test_randomquote:MyTestCase::test_pass
- test.test_randomquote:MyTestCase::test_fail
- test.test_randomquote:MyTestCase::test_something
